### ISSUE TITLE
Fails to select version when using particular commit

### ISSUE THREAD

**Issue by yyoncho** [jiro4989/setup-nim-action#305]
## Describe the bug

choosenim supports using commit id, e. g. `#branch-name`, `#commit-id`. It seems like setup-nim-action fails to do so.

## To Reproduce

```

on:
  push:
  pull_request:
  schedule:
  - cron: "0 19 * * *"

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nimversion:
          - "#version-1-6"
    name: ${{ matrix.os }} - ${{ matrix.nimversion }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1.4.1
        with:
          nim-version: ${{ matrix.nimversion }}
          yes: true
      - name: Install Mercurial on macOS
        run: nim --version

```

## Expected behavior

the correct version is installed properly

## Screenshots or Logs

https://github.com/yyoncho/langserver/actions/runs/4045771119/jobs/6957691462

- OS: any
- Version: latest

## Additional context

-
