### ISSUE TITLE
[Bug]: The nim directory can only be placed under the current directory.

### ISSUE THREAD

**Issue by jiro4989** [jiro4989/setup-nim-action#499]
### What happened?

`nim-install-direcotry` doesn't work non-current direcotry.

```yaml
nim-install-directory: ${{ runner.temp }}
```

The reason is that using `$PWD`.

```yaml
    - name: Set PATH for Unix
      shell: bash
      run: |
        echo "$PWD/${{ inputs.nim-install-directory }}/bin" >> "$GITHUB_PATH"
        echo "$HOME/.nimble/bin" >> "$GITHUB_PATH"
```
