### ISSUE TITLE
[Feature]: Cache for Nim devel

### ISSUE THREAD

**Issue by fox0430** [jiro4989/setup-nim-action#502]
### Is your feature request related to a problem? Please describe

First, I don't have experience with developing actions. 

I want to cache Nim devel (I want to use it without build). And, is this possible? example,

1. Restore compiler cache
2. Check the cache and latest git hash
3. If a different git hash, Remove the cache and build the latest compiler

I think the process will branch depending on the compiler version, but I don't know if this is common.
If you're interested in this I'd like to know your thoughts.

**Comment by jiro4989** [comment]
It's common that caching dependencies. But I think, it's uncommon that caching compiler. 

For example, [setup-go](https://github.com/actions/setup-go), [setup-java](https://github.com/actions/setup-java) and [setup-node](https://github.com/actions/setup-node) have caching dependencies. But those don't have caching compiler options.

Also, it seems impossible to install a compiler of development version.

---

I recommend using [actions/cache](https://github.com/actions/cache) if you want to cache something (compilers, dependencies or more). If it's a simple date-based volatile caching, this example might work.

```yaml
      # Create a cache key with date
      - name: Get Date
        id: get-date
        run: echo "date=$(date "+%Y-%m-%d")" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Cache nim compiler
        id: cache
        uses: actions/cache@v4
        with:
          path: .nim_runtime
          key: ${{ runner.os }}-nim-compiler-${{ steps.get-date.outputs.date }}

      # Run this actions if cache doesn't exist
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: devel
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.cache.outputs.cache-hit != 'true'
```

## References

* [Skipping steps based on cache-hit - actions/cache](https://github.com/actions/cache?tab=readme-ov-file#skipping-steps-based-on-cache-hit)
* [Setting an output parameter - GitHub Docs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)
