### ISSUE TITLE
[Feature]: Add ability to use nightly builds

### ISSUE THREAD

**Issue by ire4ever1190** [jiro4989/setup-nim-action#504]
### Is your feature request related to a problem? Please describe

Selecting devel version for tests can add a lot of time to the CI since it needs to build it from source

### Describe the solution you'd like

Add ability to use [nightly builds](https://github.com/nim-lang/nightlies/releases) so that I don't need to build the compiler from scratch

**Comment by jiro4989** [comment]
That's sounds good. I will add the feature.

**Comment by jiro4989** [comment]
@ire4ever1190 I added `use-nightlies` parameter.

https://github.com/jiro4989/setup-nim-action/releases/tag/v2.2.0

Try this example:

```yaml
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: devel
          use-nightlies: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

Ref: https://github.com/jiro4989/setup-nim-action?tab=readme-ov-file#devel-usage
