### ISSUE TITLE
[Bug]: `nimble install nimble` is not working

### ISSUE THREAD

**Issue by fox0430** [jiro4989/setup-nim-action#513]
### What happened?

I tested the workflow like this

```yaml
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 2.2.0
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: nimble install nimble
      run: |
        nimble -v

        nimble refresh
        nimble install nimble

        nimble -v
```

But result here
```
nimble v0.16.1 compiled at 2024-10-02 02:00:57
git hash: couldn't determine git hash

Downloading Official package list
    Success Package list downloaded.
Downloading https://github.com/nim-lang/nimble using git
  Verifying dependencies for nimble@0.[16](https://github.com/fox0430/moe/actions/runs/12729557687/job/35481477763#step:5:17).4
 Installing nimble@0.16.4
   Building nimble/nimble using c backend
  Success:  nimble installed successfully.

nimble v0.16.1 compiled at [20](https://github.com/fox0430/moe/actions/runs/12729557687/job/35481477763#step:5:21)24-10-02 02:00:57
git hash: couldn't determine git hash
```
nimble 0.16.4 install was successful but 0.16.1 is still used. Is it a path problem?

### Actions log url

https://github.com/fox0430/moe/actions/runs/12729557687/job/35481477763
